[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  # node_version artık bir object değil, doğrudan string bir değer olmalı.
  # Emin olmak için tırnak içine alalım.
  node_version = "18"